export const colors = {
  black: '#000',
  white: '#FFF',
  themeBackground: '#F7F7F7',
  fontMainColor: '#212121',
  fontSecondColor: '#4A4A4A',
  fontThirdColor: '#949393',
  fontBlue: '#6178DE',
  fontBrown: '#D0AD8A',
  fontPlaceholder: '#cccccc',
  iconColor: '#F48B98',
  horizontalLine: '#949393',
  medHorizontalLine: '#D8D8D8',
  lightHorizontalLine: '#f0f0f0',
  spinnerColor: '#D0AD8A',
  buttonBackground: '#D0AD8A',
  blueButton: '#6178DE',
  buttonText: '#FFF',
  selected: '#33cc33',
  container: '#FFF',
  containerDark: '#EAEAEA',
  messageBackground: 'rgba(52, 52, 52, .9)',
  primaryBlackColor: 'rgba(22, 21, 21, 0.9)',
  errorColor: '#FA7751',
  google: '#DC4E41',
  googleRedColor: '#DC4E41',
  facebook: '#3B5998',
  radioColor: '#FFF',
  radioOuterColor: '#D0AD8A',
  lightBrown: '#fcead9',
  headerbackground: '#FFF',
  headerText: '#000',
  startColor: '#D0AD8A',
  startOutlineColor: '#D0AD8A',
  blackText: '#4A4A4A',
  whiteColor: '#fff',
  brownColor: '#D0AD8A',
  blueColor: '#2962FF',
  secondaryWhiteColor: '#fff',
  greenColor: '#8CB65E',
  greenButtonColor: '#5dad07ff',
  lightBlueColor: '#6178DE',
  pinkColor: '#F48B98',
  textBlueColor: '#6178DE',
  textColor: '#7382c7ff',
  greenTextColor: '#8CB65E',
  // many shades of gray
  backgroudGray: '#F7F7F7',
  darkGrayText: '#9B9B9B',
  lightGrayColor: '#cac8c8ff',
  grayLinesColor: '#EAEAEA'
}
